In [52]:
#import libraries
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
#this is for making custom stop words
from sklearn.feature_extraction._stop_words import ENGLISH_STOP_WORDS
#train test split for training and testing duh
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
import numpy as np

In [53]:
#read csv files, give their columns titles
drawings = pd.read_csv(r"C:\Users\gramos1\OneDrive - Reworld\DrawingNames.csv",sep=',',usecols=[0, 1],header=0,names=['Drawing Title', 'Category'])
#Reading only the labeled drawings
cutdrawings = drawings[drawings['Category'].notna()].copy()

In [54]:
code_pattern = r'^[A-Za-z0-9]+[-_\s]?'
cutdrawings['Drawing Title'] = (
    cutdrawings['Drawing Title']
    .str.replace(code_pattern, '', regex=True)
    .str.lower()
)

In [55]:
custom_stop_words = list(ENGLISH_STOP_WORDS) + ['sys',
                                              'installation',
                                              'schem',
                                              'diagram',
                                                'dwg',
                                              'diag',
                                            'plans',
                                             'layout',
                                             'details',
                                              'arrgt',]

In [56]:


#vect to bring in tfidf vectorizer
#stop words is to filter noise, english here to filter out generic english

vect = TfidfVectorizer(
     #trying to get rid of english and numbers
                       stop_words= custom_stop_words,
    #filter out anything not alphabetic
                        token_pattern=r'(?u)\b[a-zA-Z]+\b',
     #put this 1-2 so i can get bigrams, might need to increase? 1-3?
                      ngram_range=(1,3),
     #I want features to be words i think
                    analyzer = 'word',
      #min_df to try and filter out irrelevant words? usually drawings are in batches so if it's
        #Not important enough to be in a batch then dont count it
                     min_df=1,)

#fit_transform applied to drawing title names,
#Learn vocabulary and idf, return document-term matrix.
X = vect.fit_transform(cutdrawings['Drawing Title'])

In [57]:
#output of feature names for transformation
#(texts turns into numerical features)
print(vect.get_feature_names_out()[:200])

['ab' 'ab record' 'absorber' 'absorber bott' 'absorber bott cone'
 'absorber brackets' 'absorber chain' 'absorber chain tensioner'
 'absorber cone' 'absorber cone sub' 'absorber elev'
 'absorber elev orientation' 'absorber field' 'absorber field bolt'
 'absorber girder' 'absorber girder section' 'absorber lower'
 'absorber lower shellsub' 'absorber manway' 'absorber manway frame'
 'absorber misc' 'absorber misc clips' 'absorber riser'
 'absorber riser scrubber' 'absorber riser section' 'absorber scraper'
 'absorber scraper ring' 'absorber scrubber' 'absorber scrubber pre'
 'absorber shell' 'absorber shell manway' 'absorber shim'
 'absorber shim packs' 'absorber shop' 'absorber shop ass'
 'absorber upper' 'absorber upper shell' 'absorbers' 'absorbers platforms'
 'ac' 'ac dc' 'ac dc interlocks' 'ac power' 'ac power cubicle' 'ac pwr'
 'ac pwr analyzer' 'ac regulator' 'ac regulator sh' 'ac schematic' 'acces'
 'acces openings' 'acces openings scrubber' 'access' 'access collector'
 'access collector elev' 'access collector plan' 'access door'
 'access door platform' 'access door sh' 'access floor'
 'access floor openings' 'access grading' 'acid' 'acid cation'
 'acid cation gen' 'acid pumps' 'acid pumps sch' 'acid regeneration'
 'acid regeneration general' 'acid storage' 'acid storage tank'
 'acid tank' 'acid tank area' 'acid tank block' 'acid tank ext'
 'acid tank waste' 'add' 'add l' 'add l pile' 'addition' 'addition steel'
 'addition steel floor' 'additional' 'additional handrail'
 'additional handrail floor' 'adjuster' 'adjuster sh' 'admin' 'admin ash'
 'admin ash handling' 'admin bldgs' 'admin bldgs fdn' 'advise'
 'advise reloc' 'advise reloc steel' 'aftercoolers' 'ai' 'ai special'
 'ai special filter' 'air' 'air block' 'air block cable' 'air blower'
 'air blower motor' 'air bnr' 'air bnr ext' 'air boiler' 'air boiler b'
 'air cold' 'air cold st' 'air compressor' 'air compressor s'
 'air compressors' 'air compressors c' 'air compressors lube'
 'air comressors' 'air comressors solenoid' 'air conditiong'
 'air conditiong unit' 'air conn' 'air cooled' 'air cooled condenser'
 'air cooled condensers' 'air cooled steam' 'air ejtr' 'air ejtr sh'
 'air ext' 'air ext conn' 'air fan' 'air fan conn' 'air fan misc'
 'air fan sch' 'air filtering' 'air filtering point' 'air filtering sh'
 'air heater' 'air heaters' 'air heaters elem' 'air htr' 'air inlet'
 'air inlet boiler' 'air instrmntn' 'air instrmntn ctl' 'air intake'
 'air intake silencer' 'air misc' 'air misc conn' 'air pressure'
 'air pressure duct' 'air prim' 'air prim air' 'air purge'
 'air purge plan' 'air receiver' 'air receiver tank' 'air roller'
 'air roller grates' 'air secdry' 'air secdry air' 'air secdry bnr'
 'air sh' 'ala' 'ala c' 'alarm' 'alarm interconn' 'alarm plant'
 'alarm plant loop' 'alert' 'alert danger' 'alert danger relay' 'alt'
 'alt sect' 'alternate' 'alternate scheme' 'alternate scheme refuse'
 'amine' 'amine feed' 'amine tanks' 'amm' 'amm ctl' 'amm ctl skid'
 'amm tank' 'amm tank pumps' 'ammonia' 'ammonia injection'
 'ammonia injection block' 'ammonia injection connection'
 'ammonia storage' 'ammonia storage pwr' 'ammonia storage tank'
 'ammonia supply' 'ammonia supply pump' 'ammonia tank' 'analyzer'
 'analyzer temp' 'analyzer temp monitor' 'anchor' 'anchor bolt'
 'anchor bolt id' 'anchor bolt mk']

In [58]:
#prints out matrix with feature values, many will be zero, presented in this way to save memory
#remember matrix is one row per document and one col per token
#value = tfidf score 0-1, and the score quantifies how important that word is to the title
print(X[:50])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 796 stored elements and shape (50, 6040)>
  Coords	Values
  (0, 3354)	0.20175249083394847
  (0, 1837)	0.2112687370295476
  (0, 5132)	0.17882384893500133
  (0, 3086)	0.2112687370295476
  (0, 1468)	0.16031229704179017
  (0, 1656)	0.16276371746594478
  (0, 2985)	0.22468113273289558
  (0, 4828)	0.10245044864155244
  (0, 3357)	0.2476097746318427
  (0, 1842)	0.2476097746318427
  (0, 5147)	0.2476097746318427
  (0, 3087)	0.2112687370295476
  (0, 1475)	0.20616958083968442
  (0, 1657)	0.2341973789284947
  (0, 2988)	0.2341973789284947
  (0, 3358)	0.2476097746318427
  (0, 1843)	0.2476097746318427
  (0, 5148)	0.2476097746318427
  (0, 3088)	0.22468113273289558
  (0, 1476)	0.2341973789284947
  (0, 1658)	0.2341973789284947
  (1, 5132)	0.3238103475852466
  (1, 1468)	0.1451450154340427
  (1, 1656)	0.1473645049046882
  (1, 4828)	0.09275752530341683
  :	:
  (47, 5333)	0.31674134730412823
  (48, 812)	0.20390139276699698
  (48, 520)	0.1941338233673439
  (48, 813)	0.20910862331964122
  (48, 5313)	0.21022251175477205
  (48, 4809)	0.2216386591229241
  (48, 5329)	0.2329245778688678
  (48, 1267)	0.13587342316261444
  (48, 528)	0.32153208842663966
  (48, 817)	0.32153208842663966
  (48, 2578)	0.22941644917553783
  (48, 4818)	0.29504095466812247
  (48, 2589)	0.29504095466812247
  (48, 4819)	0.29504095466812247
  (48, 2590)	0.29504095466812247
  (48, 5333)	0.32153208842663966
  (49, 892)	0.18724527404667055
  (49, 5313)	0.2452137541761266
  (49, 4809)	0.25853010327216447
  (49, 5329)	0.2716945473743635
  (49, 1162)	0.3909357186902116
  (49, 4814)	0.3909357186902116
  (49, 1163)	0.3909357186902116
  (49, 5331)	0.3909357186902116
  (49, 4815)	0.3909357186902116

In [59]:
#time to split up data
y = cutdrawings['Category']
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size = 0.33, random_state = 42)

In [60]:
# Initialize and train the classifier
clf = SVC(kernel='linear')
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [61]:
#predict on test set
y_pred = clf.predict(X_test)

#evaluate performance
accuracy = accuracy_score(y_test,y_pred)
report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy:.4f}')
print('Classification Report:')
print(report)

Accuracy: 0.8522
Classification Report:
                               precision    recall  f1-score   support

                  Ash Removal       0.94      1.00      0.97        17
               Auxilary Water       0.63      0.86      0.73        14
   Boiler and Steam Generator       0.76      0.96      0.85        26
    Boiler-Furnace Combustion       1.00      0.80      0.89        20
             Carbon Injection       1.00      0.93      0.96        44
        Closed Cooling System       1.00      0.70      0.82        10
            Condensate System       1.00      0.64      0.78        11
                        DENOX       1.00      0.80      0.89        10
       Digital Control System       1.00      0.92      0.96        25
      Electrical Distribution       0.79      0.98      0.88        50
                Environmental       1.00      0.40      0.57         5
                    Feedwater       1.00      0.75      0.86         4
              Fire Protection       0.86      0.55      0.67        11
                     Fuel Oil       0.00      0.00      0.00         2
                    Generator       1.00      0.50      0.67         4
              Layout/Planning       0.67      0.98      0.80        66
             Lime Slurry Prep       1.00      0.92      0.96        12
                 Main Turbine       1.00      0.79      0.88        14
               Main/Aux Steam       0.93      0.76      0.84        17
              Metals Recovery       1.00      0.80      0.89        15
                Miscellaneous       0.00      0.00      0.00         1
Refuse Receiving and Handling       1.00      0.92      0.96        12
                     Scrubber       1.00      0.88      0.93        24
                  Service Air       1.00      0.33      0.50         3
              Water Treatment       0.00      0.00      0.00         3
 Water Treatment and Sampling       1.00      0.46      0.63        13

                     accuracy                           0.85       433
                    macro avg       0.83      0.68      0.73       433
                 weighted avg       0.88      0.85      0.85       433

C:\Users\gramos1\AppData\Local\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\gramos1\AppData\Local\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\gramos1\AppData\Local\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [62]:
def predict_category(text):

    text_vec = vect.transform([text])
    prediction = clf.predict(text_vec)
    return prediction[0]

In [63]:
drawings.head()

                                       Drawing Title           Category
0  BIC-0200 - INSTRMNTN & CONTROL DIAGS. SYMB. & ...                NaN
1  BIC-0201 - MAIN & DUMP STM SYS. INSTRMNTN & CT...     Main/Aux Steam
2  BIC-0202 - EXT. STM & AUX. STM SYS. INSTRN & C...     Main/Aux Steam
3  BIC-0203 - FEEDWATER SYS. INSTRMTN & CTL DIAGS...          Feedwater
4  BIC-0204 - CONDS & MKE - UP WATER SYS. INSTR &...  Condensate System

In [64]:
cutdrawings.head()

                                       Drawing Title               Category
1  0201 - main & dump stm sys. instrmntn & ctl di...         Main/Aux Steam
2  0202 - ext. stm & aux. stm sys. instrn & ctl d...         Main/Aux Steam
3  0203 - feedwater sys. instrmtn & ctl diags ind...              Feedwater
4  0204 - conds & mke - up water sys. instr & ctl...      Condensate System
5  0205 - clsd loop cooling h20 sys instr & ctl d...  Closed Cooling System

In [65]:
# Next step is to fix this so it doesnt take the cut down version and actually sorts through all 5000 entries

completetfidf = vect.transform(drawings['Drawing Title'])
completepredictions = clf.predict(completetfidf)
drawings['Prediction'] = completepredictions

In [66]:
drawings['Accurate?'] = np.where((drawings['Category'] == drawings['Prediction']),1,0)

In [67]:
drawingpredictions = pd.DataFrame(drawings[['Drawing Title','Category','Prediction','Accurate?']])
file_name = 'OutputPredictions.xlsx'
drawingpredictions.to_excel(file_name)